name: Telepowort
author: Lykio_Frostpaw
main: dreamers.lykiofrostpaw.plugin.Telepowort
version: 0.1b
api-version: 1.14
commands:
  home:
    usage: /home <home>
    description: Teleports you to home you set previously.
  delhome:
    usage: /delhome <home>
    description: Deletes a home.
  sethome:
    usage: /sethome <name>
    description: Private warp.
  tpa:
    usage: /tpa <player>
    description: Teleports you to a player with permission.
  tpahere:
    usage: /tpahere <player>
    description: Teleports a player to you with permission.
  tpaccept:
    usage: /tpaccept
    description: Permits a tpa or tpahere.
  tpadecline:
    usage: /tpadecline
    description: Won't permit a tpa or tpahere.
  warp:
    usage: /warp <warp>
    description: Teleports the player to a warp.
  setwarp:
    usage: /setwarp <name>
    description: https://media.tenor.com/images/fa3143e89d76490bdf83835cbd3d9fed/tenor.gif
  delwarp:
    usage: /delwarp <warp>
    description: Deletes a warp.
  nickname:
    usage: /nick <nickname>
    description: Gives you a nickname.
  ping:
    usage: /ping
    description: Currently pongs - will eventually actually return latency. One day.
  treload:
    usage: /treload
    description: Reloads telepowort.