name: Telepowort
author: Lykio_Frostpaw
main: dreamers.lykiofrostpaw.plugin.Telepowort
version: 0.91r
api-version: 1.14
commands:
  home:
    usage: /home <home>
    description: Teleports you to home you set previously.
    aliases:
      - h
  delhome:
    usage: /delhome <home>
    description: Deletes a home.
    aliases:
      - delh
  sethome:
    usage: /sethome <name>
    description: Private warp.
    aliases:
      - seth
  tpa:
    usage: /tpa <player>
    description: Teleports you to a player with permission.
  tpahere:
    usage: /tpahere <player>
    description: Teleports a player to you with permission.
    aliases:
      - tph
  tpaccept:
    usage: /tpaccept
    description: Permits a tpa or tpahere.
    aliases:
      - tpy
  tpadecline:
    usage: /tpadecline
    description: Won't permit a tpa or tpahere.
    aliases:
      - tpn
  warp:
    usage: /warp <warp>
    description: Teleports the player to a warp.
    aliases:
      - w
  setwarp:
    usage: /setwarp <name>
    description: https://media.tenor.com/images/fa3143e89d76490bdf83835cbd3d9fed/tenor.gif
    aliases:
      - setw
  delwarp:
    usage: /delwarp <warp>
    description: Deletes a warp.
    aliases:
      - delw
  nickname:
    usage: /nick <nickname>
    description: Gives you a nickname.
    aliases:
      - nick
  ping:
    usage: /ping
    description: Currently pongs - will eventually actually return latency. One day.
  treload:
    usage: /treload
    description: Reloads telepowort.
  back:
    usage: /back
    description: Will send you back to where you were prior to being teleported.
    aliases:
      - b